### ISSUE TITLE
Deleting search does not reset search

### ISSUE THREAD

**Issue by Subtixx** [dracula/draculatheme.com#255] opened 2023-10-13 03:35 UTC
Hey first great new website! Looking real good!

I tried to search: "wind" got 2 results:
![image](https://github.com/dracula/draculatheme.com/assets/20743379/c1f2d838-4cb9-4df4-8253-fac30cee077c)

Pressing backspace until "wi" is in the search:
![image](https://github.com/dracula/draculatheme.com/assets/20743379/618d1d04-8898-4a68-bcea-88edd7640dce)

It only ever shows 2 results. If I do "windows" it shows none even though "Windows Terminal" should be one:
![image](https://github.com/dracula/draculatheme.com/assets/20743379/d15e3c2d-33aa-42b6-81b4-c48c9dfd21ed)

If I then press backspace until "wi" shows I get no results:
![image](https://github.com/dracula/draculatheme.com/assets/20743379/55b18e76-1a65-4528-a634-0240f349cce7)

PS:
This is the list that shows in a fresh search using "wi":
![image](https://github.com/dracula/draculatheme.com/assets/20743379/e7b70e5b-e71d-4e6f-910e-fa6368dd3f22)

**Comment by luxonauta** [comment] 2023-11-06 18:56
✅ A commit with a partial version of a resolution was made here: [#3c8eb3a](https://github.com/dracula/draculatheme.com/commit/3c8eb3a8453d543b8dd18b8254349c623e93b0b4)

The problem is pending in the CMDK project, on re-render specifically. Although I haven't been able to resolve it entirely, feel free to make suggestions and even PR; I will close the issue for now.

**Closed by luxonauta** 2023-11-06 18:56 UTC
Labels: enhancement
